### ISSUE TITLE
Switching to hex/dec/bin output hangs GUI

### ISSUE THREAD

**Issue by danbim** [wisebed/wisegui#40] opened 2012-09-24 09:06 UTC
Sometimes it is not even possible to close the browser tab (Chrome)

**Comment by master-lincoln** [comment] 2012-09-25 09:39
Quasi duplicate of #39...Should be way better now after #41 (at least on modern machines)

**Comment by danbim** [comment] 2012-09-25 09:47
Not really a duplicate! Even if performance is made better there still may be the issue (e.g. on not-so-modern machines or machines under load) that the GUI hangs. We need a workaround here that keeps the GUI responsive!

**Closed as completed** 2012-09-25 10:05 UTC
Labels: Defect, High Priority
